# Generated by Django 3.2.7 on 2021-09-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
